<a href="https://colab.research.google.com/github/vidyawadhai13/python-projects/blob/main/Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# (a) Generate 4×4 Identity Matrix
import numpy as np

identity_matrix = np.eye(4)

print("4x4 Identity Matrix:")
print(identity_matrix)

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# (b) Generate Two 3×3 Random Matrices and Perform Addition & Multiplication
import numpy as np

matrix1 = np.random.randint(1, 10, (3, 3))
matrix2 = np.random.randint(1, 10, (3, 3))

print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

addition = matrix1 + matrix2
print("\nMatrix Addition:")
print(addition)

multiplication = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication:")
print(multiplication)

Matrix 1:
[[5 3 6]
 [1 7 2]
 [5 1 8]]

Matrix 2:
[[2 5 1]
 [9 7 9]
 [2 7 6]]

Matrix Addition:
[[ 7  8  7]
 [10 14 11]
 [ 7  8 14]]

Matrix Multiplication:
[[49 88 68]
 [69 68 76]
 [35 88 62]]


In [6]:
# Multiply 5×3 Matrix by 3×2 Matrix (User Input)
import numpy as np

print("Enter elements for 5x3 Matrix:")

matrix1 = []
for i in range(5):
    row = list(map(int, input(f"Enter 3 elements for row {i+1}: ").split()))
    matrix1.append(row)

matrix1 = np.array(matrix1)

print("\nEnter elements for 3x2 Matrix:")

matrix2 = []
for i in range(3):
    row = list(map(int, input(f"Enter 2 elements for row {i+1}: ").split()))
    matrix2.append(row)

matrix2 = np.array(matrix2)

product = np.dot(matrix1, matrix2)

print("\n5x3 Matrix:")
print(matrix1)

print("\n3x2 Matrix:")
print(matrix2)

print("\nProduct Matrix (5x2):")
print(product)

Enter elements for 5x3 Matrix:
Enter 3 elements for row 1: 10 11 12 
Enter 3 elements for row 2: 13 14 15
Enter 3 elements for row 3: 16 17 18
Enter 3 elements for row 4: 19 20 21
Enter 3 elements for row 5: 22 23 24

Enter elements for 3x2 Matrix:
Enter 2 elements for row 1: 25 26
Enter 2 elements for row 2: 27 28
Enter 2 elements for row 3: 29 30

5x3 Matrix:
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]]

3x2 Matrix:
[[25 26]
 [27 28]
 [29 30]]

Product Matrix (5x2):
[[ 895  928]
 [1138 1180]
 [1381 1432]
 [1624 1684]
 [1867 1936]]
